add required (node.js) in correct version (#9)
to run the command: `./gradlew clean build -Pvaadin.productionMode` node.js must be in an outdated version (16.10.0). The new versions have the following error:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webui:vaadinBuildFrontend'.
> Command '/usr/local/bin/node /home/john/Downloads/taskadapter/webui/node_modules/webpack/bin/webpack.js' failed with exit code 1: node:internal/crypto/hash:71
    this[kHandle] = new _Hash(algorithm, xofLen);
                    ^
  
  Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:71:19)
      at Object.createHash (node:crypto:140:10)
      at module.exports 

with this, it is possible to build the program correctly